version: "2.1"
services:
  zxt:
    volumes:
      - ./log:/var/log/nginx
      - ./html:/var/www/html
      - ./run:/run/php
      - ./flagggggggggggggg_1s_here:/flagggggggggggggg_1s_here
    build: .
    restart: always
    ports:
      - "80:80"
